# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5d1bc19b80df7275cd2db15955ce86183982cb3572daf3b4098204bcd519694c7560b24325aad6228ad1cc47f09a721c3892eb84d346cb87f60c543de2dd8310

test:
  secret_key_base: a0ad34fd248c1c7e3ba7391ad66a2bb3bf91748c00e6b9c3b185d34d241a9b2f0a9f9f63996830b3b7760012ab836da5b607dd4bd68a90004f2744b3b73eb70c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
